---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argocd-repo-server-encrypted"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:danmanners/homelab-kube-cluster.git"
    path: tekton/argocd-repo-server-encrypted
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
