---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: argocd-repo-server-build
  namespace: tekton-pipelines
spec:
  serviceAccountName: argocd-repo-server-encrypted
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: nfs-client
  timeout: 1h0m0s
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: https://github.com/danmanners/argocd-sops
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: buildah
      params:
        - name: DOCKERFILE
          value: Containerfile
        - name: IMAGE
          value: ghcr.io/danmanners/argo-repo-server:aws-ksops-v2.2.2
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
  taskRunSpecs:
    - pipelineTaskName: buildah
      taskPodTemplate:
        nodeSelector:
          kubernetes.io/arch: amd64
