---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines

resources:
  # Triggers
  - https://github.com/tektoncd/triggers/releases/download/v0.20.2/release.yaml
  - https://github.com/tektoncd/triggers/releases/download/v0.20.2/interceptors.yaml
