---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-builder-excalidraw
  namespace: tekton-pipelines
spec:
  storageClassName: ssd-nrs
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
# Pipeline - Build a container and push it up to the definied container registry
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-and-build
  namespace: tekton-pipelines
spec:
  # Paramaters
  params:
    - name: gitUrl
      type: string
      default: https://github.com/excalidraw/excalidraw.git
    - name: gitRevision
      type: string
      default: v0.12.0
    - name: containerRegistry
      type: string
      default: ghcr.io
    - name: containerName
      type: string
      default: danmanners/excalidraw

  # Workspaces
  workspaces:
    - name: ws
    - name: dockerfile
      configMap:
        name: excalidraw

  # Steps
  tasks:
    # Initial Step
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
      workspaces:
        - name: output
          workspace: ws

    - name: copy-file
      taskRef:
        - name: write-file
      workspaces:
        - name: source
          workspace: dockerfile
        - name: dest
          workspace: ws
      runAfter:
        - git-clone
      params:
        - name: source-path
          value: /excalidraw/Dockerfile
        - name: dest-path
          value: $(workspaces.ws.path)/Dockerfile

    # After Initialization
    - name: buildah-amd64
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: ws
        - workspace: dockerfile
      runAfter:
        - git-clone
        - copy-file
      params:
        - name: IMAGE
          value: "$(params.containerRegistry)/$(params.containerName)"
      nodeSelector:
        kubernetes.io/arch: amd64

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: excalidraw
  generateName: excalidraw-
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-user
  pipelineRef:
    name: clone-and-build
  workspaces:
    - name: ws
      persistentVolumeClaim:
        claimName: tekton-builder-excalidraw
    - name: dockerfile
      configMap:
        name: excalidraw
        items:
          - key: Dockerfile
            path: /excalidraw/Dockerfile
