---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-builder-excalidraw-2
  namespace: tekton-pipelines
spec:
  storageClassName: ssd-nrs
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: excalidraw2
  generateName: excalidraw2-
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-user
  pipelineRef:
    name: clone-and-build
  taskRunSpecs:
    # Build the amd64 image on dedicated amd64 hardware
    - pipelineTaskName: amd64
      taskPodTemplate:
        nodeSelector:
          kubernetes.io/arch: amd64
    # Build the arm64 image on dedicated arm64 hardware
    - pipelineTaskName: arm64
      taskPodTemplate:
        nodeSelector:
          kubernetes.io/arch: arm64
    # Faster Networking on the amd64 nodes
    - pipelineTaskName: push
      taskPodTemplate:
        nodeSelector:
          kubernetes.io/arch: amd64
  workspaces:
    - name: ws
      persistentVolumeClaim:
        claimName: tekton-builder-excalidraw-2
    - name: dockerfile
      configMap:
        name: excalidraw
        items:
          - key: Dockerfile
            path: Dockerfile
    - name: containers
      volumeClaimTemplate:
        spec:
          storageClassName: ssd-nrs
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 2Gi
