---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines

resources:
  # Git Clone
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.5/git-clone.yaml
  # Buildah
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/buildah/0.3/buildah.yaml