---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: replace-text
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: replace-text
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: replace-text
    tekton.dev/platforms: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    Runs a sed command to edit the contents of a file.
  params:
    - name: FILENAME
      description: Name of the file to be edited
    - name: SED_COMMAND
      description: the sed command to be executed
    - name: IMAGE
      description: The container image to use for sed
      default: docker.io/library/alpine:3.15
  workspaces:
    - name: source
  steps:
    - name: replace
      image: $(params.IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        sed -i "$(params.SED_COMMAND)" $(params.FILENAME)
