---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 10.45.0.254
      peer-asn: 65529
      my-asn: 65528
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.56.1.1-10.56.255.254
