---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - configMap.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.11/manifests/namespace.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.11/manifests/metallb.yaml

patchesStrategicMerge:
  - patches/DaemonSet.yaml
