---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-dockerconfig
  annotations:
    policies.kyverno.io/title: Sync .dockerconfigjson secrets
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      This policy will copy a Secret called `ghcr-io` which
      exists in the `default` Namespace every other Namespace
      when they are created. It will also push updates of the
      copied Secret should the source Secret be changed.
spec:
  mutateExistingOnPolicyUpdate: true
  generateExistingOnPolicyUpdate: true
  rules:
    - name: sync-ghcr-io-dockerconfigjson
      match:
        resources:
          kinds:
            - Namespace
      generate:
        apiVersion: v1
        kind: Secret
        name: ghcr-io
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        clone:
          name: ghcr-io
          namespace: default
