---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines

resources:
  # Git Clone - https://hub.tekton.dev/tekton/task/git-clone
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.5/git-clone.yaml
  # Git CLI - https://hub.tekton.dev/tekton/task/git-cli
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-cli/0.3/git-cli.yaml
  # Buildah - https://hub.tekton.dev/tekton/task/buildah
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/buildah/0.3/buildah.yaml
  # Kubernetes Actions https://hub.tekton.dev/tekton/task/kubernetes-actions
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/kubernetes-actions/0.2/kubernetes-actions.yaml
