---
- hosts: control_plane_db
  gather_facts: yes
  become: yes
  roles:
    - role: geerlingguy.postgresql
    - role: postgres_db_setup

- hosts: k3s_aarch64
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspi

- hosts: control_plane_nodes:k3s_x64
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download

- hosts: control_plane_nodes
  become: yes
  roles:
    - role: k3s/control-plane

- hosts: k3s_workers
  become: yes
  roles:
    - role: k3s/worker
