- hosts: k3s_cluster
  # gather_facts: yes
  become: yes
  tasks:
    - name: Enable and check K3s service
      systemd:
        name: k3s
        daemon_reload: yes
        state: stopped
        enabled: no
      ignore_errors: yes
      when: "'control_plane_nodes' in group_names"

    - name: Enable and check K3s service
      systemd:
        name: k3s-node
        daemon_reload: yes
        state: stopped
        enabled: no
      ignore_errors: yes
      when: "'k3s_workers' in group_names"

    - name: Remove K3s Data from /var/lib/rancher
      ansible.builtin.file:
        path: /var/lib/rancher/k3s
        state: absent
      when: "'k3s_cluster' in group_names"

    - name: Remove K3s Data from /etc/rancher
      ansible.builtin.file:
        path: /etc/rancher/k3s
        state: absent
      when: "'k3s_cluster' in group_names"
