global:
  nameOverride: jenkins

image:
  repository: jenkins-container-image
  tag: latest
  pullPolicy: IfNotPresent

nodeSelector:
  kubernetes.io/arch: amd64

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

termination:
  gracePeriodSeconds: 60

resources:
  limits:
    cpu: "2"
  requests:
    cpu: "1"

# initContainers:
#   init-jenkins:
#     image: docker.io/library/busybox:stable
#     command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
#     volumeMounts:
#     - name: jenkins-home
#       mountPath: /var/jenkins_home
#       subPath: jenkins-volume

service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        enabled: false
      web:
        enabled: true
        port: 8080
        protocol: TCP
      jnlp-agents:
        enabled: true
        port: 50000
        protocol: TCP

ingress:
  main:
    enabled: true
    ingressClassName: nginx
    tls:
    - secretName: jenkins-cert
      hosts:
      - jenkins.homelab.danmanners.com
    hosts:
    - host: jenkins.homelab.danmanners.com
      paths:
      - path: /
        pathType: Prefix
        service:

persistence:
  jenkins-home:
    enabled: true
    storageClass: ceph-rbd
    accessMode: ReadWriteOnce
    mountPath: /var/jenkins_home
    subPath: jenkins-volume
    size: 20Gi
