---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines

resources:
  # Traefik Ingress
  - ingress.yaml
  # Tasks Subdirectory
  - tasks
  # Feature Flags
  - feature-flags.yaml
  # Main Install
  - dashboard
  - pipelines
  - triggers
