---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines

resources:
  # Traefik Ingress
  - ingress.yaml
  - ingress-ro.yaml
  # Tasks Subdirectory
  - tasks/
  # Main Install
  - dashboard
  - pipelines
  - triggers

patchesStrategicMerge:
  # Feature Flags
  - feature-flags.yaml
