---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton

resources:
  # Traefik Ingress
  - ingress.yaml
  # Pipelines
  - https://github.com/tektoncd/pipeline/releases/download/v0.37.3/release.yaml
  # Triggers
  - https://github.com/tektoncd/triggers/releases/download/v0.20.2/release.yaml
  - https://github.com/tektoncd/triggers/releases/download/v0.20.2/interceptors.yaml
  # Dashboard
  - https://github.com/tektoncd/dashboard/releases/download/v0.28.0/tekton-dashboard-release.yaml
  # Tasks Subdirectory
  - tasks
