---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: "15.4.4"
    chart: kube-prometheus-stack
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
