---
## Excalidraw
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "node-feature-discovery"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:danmanners/homelab-k3s-cluster.git"
    path: manifests/workloads/node-feature-discovery
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: node-feature-discovery
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
