---
## Excalidraw
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "open-policy-agent"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:danmanners/homelab-k3s-cluster.git"
    path: manifests/workloads/open-policy-agent
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
