---
## Nexus
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argocd"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:danmanners/homelab-kube-cluster.git"
    path: manifests/argocd
    targetRevision:     targetRevision: main

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
