---
## Nexus
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "traefik"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/danmanners/homelab-k3s-cluster.git"
    path: manifests/workloads/traefik-helm
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
