apiVersion: v1
kind: Secret
metadata:
    name: artifactory-creds
stringData:
    bootstrap.creds: ENC[AES256_GCM,data:4YU3pgeIAqZw2cPcMenyCEpKDqe6MfWlDMDSf9LBU2BTL1yvMz/ckgpV/yOdBVk=,iv:HvSivE6oC0l/3qeF0bQDqFuT7wYqeBTani5EGQMK844=,tag:MOLeuVKIRDOrH4Na552Uug==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2022-08-07T17:58:37Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwGGIwFLhXxsML9Se+f9sJiMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbKSAbRBvapGvOUUHAgEQgDt2+XhRhjtzmaACvZhBbq2C79RTibRwIqRMCvVl23R1ZZtZElAl8QpmkGlvD5pRUW1eTHd1Wi1/A6WLDA==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-07T17:58:37Z"
    mac: ENC[AES256_GCM,data:KjWsGYkvu1p6jvRj2qmWFxPHaWG4j82FkLwuldbXwh/Z/xzJ6gtS2X4RBXAZepaa+HxLP6w5kocJAHffrot04dni5jcTlYmEu0+xsXda3VXinSTEO+lFF7lB4zHad3hqGh6i3rOrI4l/aeq3Ezv3Ukeg/s7n83JQu5mq69HH/Os=,iv:EuINncJWvdKUVrbglwPHaUaEFN6zto2N1tezuQifo5A=,tag:uvOgLUPOsyMiZsSdljauIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
