apiVersion: v1
kind: Secret
metadata:
    name: dex-config
stringData:
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:MOQ4dfILKWQ6hO7l83TzsmCylpk=,iv:bqPm0nGv0r0sBjo8enj5L5l7cSFhdQVePppPywczA4c=,tag:8W7l3qv7JdU05Itv0dywHA==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:jXTFWaXQ7DGiW5ENmt5czTrjGDfM1WMowYzeoEuhIt30qAFMMK5JWg==,iv:/hrz4Ot8gL415qJJx/mDz/+eFrGdS8YM6qKZWoqEnkY=,tag:ti+ggOyvj/ET4XE8BUwiqw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2021-12-03T04:35:14Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwGC7AGFyHKx9QsEbEfIkCadAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCrAEHd3HLtFsCfyYAgEQgDtDkFNGjbK/F5Gw0kVK9qjlBRJjw0aXQRjKI1WFvq0ruSaw06KA7J8kT+8c80QUDiHLDa8yxOsSkRmt7Q==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-03T04:35:14Z"
    mac: ENC[AES256_GCM,data:rGzd3X8v/oiLa8WzruEaZRAS0sy0v5rn3gQqmGQ0mB99XUDDKcyTsMkZnTGOTaQyojoTEWy4gwpxgPljXkFb+sks4qD8b+Y6iuvBbaR7kmzXmvSrVkXANJgc+kbBh2NTLl6m5p2lioA3oZ++1lcT9fMNTH/eaCu/e/CZkXnsW5U=,iv:pj8xqV7Ua4QOm3QtynYeCMTCHIm5MllwSQ4ZnITYyKQ=,tag:23UlKn0HxiCayNu7Spf/zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
