# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: github-rss

generators:
- helm-charts/danmanners.homelab-kube-repo.yaml

# patches:
# - path: image-patch.yaml
