---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-events
bases:
  - github.com/argoproj/argo-events/manifests/cluster-install?ref=release-1.5
resources:
  - namespace.yaml
