---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

HelmChartInflationGenerator:
  - chartName: monitoring
    chartRepoUrl: https://prometheus-community.github.io/helm-charts
    chartVersion: 33.1.0
    releaseName: kube-prometheus-stack
    releaseNamespace: kube-system
    values: values.yaml

bases:
  - crds

resources:
  - rendered-helm.yaml
  - ingress.yaml
  - service.yaml
