---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines

resources:
  # Pipelines
  - https://github.com/tektoncd/pipeline/releases/download/v0.37.3/release.yaml
