---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ots

resources:
  - rendered-helm.yaml

patchesStrategicMerge: 
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: redis-redis-cluster
    $patch: delete
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: redis-redis-cluster-default
    $patch: delete