---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: excalidraw

resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml

images:
  - name: excalidraw-image
    newName: ghcr.io/danmanners/excalidraw
    newTag: 0a89c4b
