---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: excalidraw

resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  # - horizontal-pod-autoscaler.yaml
