---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft

bases:
  - helm

resources:
  - ns.yaml
  - pv.yaml

generators:
  - secrets-generator.yaml

patchesStrategicMerge:
  # Remove the Persistent Volume; let the PVC provision it.
  - |-
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: minecraft-minecraft-datadir
    $patch: delete
