---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft

resources:
  - helm
  - ns.yaml
  - pv.yaml

generators:
  - secrets-generator.yaml

patchesStrategicMerge:
  # Remove the Persistent Volume; let the PVC provision it.
  - |-
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: minecraft-minecraft-datadir
    $patch: delete
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: minecraft-minecraft
    spec:
      template:
        spec:
          containers:
            - name: minecraft-minecraft
              env:
                - name: OPS
                  value: DanManners,Megglomania,stubborntexan,blobjamesblob
