# Source: minecraft/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
    name: minecraft-minecraft
    labels:
        app: minecraft-minecraft
        chart: minecraft-3.8.0
        release: minecraft
        heritage: Helm
type: Opaque
stringData:
    rcon-password: ENC[AES256_GCM,data:NJp5WAs/Fc3C+wzSBI9YL9MZk8NV9CYq+XEzW+VNWUo=,iv:JUCSVc6y27tcjHVxy+d2QLEZ6yasILQ4UlbaVkQ1tGM=,tag:LtW8lw3/K9lWhhbFoYgVSA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2022-02-26T00:22:36Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwEaXecT0E71MSJ8zRklbrkkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUGSQrSy6fAjf/aTOAgEQgDtf5XAV/QyjAHKw1nbxlEf9g8z5ZQ7PkqaZBWT68rZeO0MlZBNDCBnajhu6MIgqSsDZxZCZm5mG2Sjicw==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-26T00:22:36Z"
    mac: ENC[AES256_GCM,data:gob82gBM7aeho74RWSs7ocTtGKSrVc958Oj0+nZhRS7LZI732VHIk79nKlswTpXfzASMZnGGceLDLCF3E1B8zjGstpEM5nCHjWo/9Byrk2uleNh7EYyfwSA7iK7IRgKTo9zgRrLUlkt1jzQGH9J4GL/452u11elAZlAh+HwRKgk=,iv:KDHGTwCz8SXygtGdzdWJ5uXIDR+IUy5fM9u8zMsXOMc=,tag:qt6w8n07qN+UAB/Ytyo4/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
