---
# apiVersion: externaldns.k8s.io/v1alpha1
# kind: DNSEndpoint
# metadata:
#   name: danmanners-dot-com
#   namespace: kube-system
# spec:
#   endpoints:
#   - dnsName: danmanners.com
#     recordTTL: 300
#     recordType: A
#     targets:
#     - "134.209.45.126"  # DigitalOcean - Host 1 ~$20/month
#     - "35.212.113.40"   # Google Cloud - Host 2 ~$11/month
---
kind: Service
apiVersion: v1
metadata:
  name: external-ip-1
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: danmanners.com
spec:
  type: ExternalName
  externalName: 35.212.94.125
---
kind: Service
apiVersion: v1
metadata:
  name: external-ip-2
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: danmanners.com
spec:
  type: ExternalName
  externalName: 134.209.45.126
