---
# apiVersion: externaldns.k8s.io/v1alpha1
# kind: DNSEndpoint
# metadata:
#   name: danmanners-dot-com
#   namespace: kube-system
# spec:
#   endpoints:
#   - dnsName: danmanners.com
#     recordTTL: 300
#     recordType: A
#     targets:
#     - "134.209.45.126"  # DigitalOcean - Host 1 ~$20/month
#     - "35.212.113.40"   # Google Cloud - Host 2 ~$11/month
---
kind: Service
apiVersion: v1
metadata:
  name: external-ip-aws
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kube.danmanners.com
  labels:
    provider: AWS
spec:
  type: ExternalName
  externalName: 54.158.27.71
---
kind: Service
apiVersion: v1
metadata:
  name: external-ip-azure
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kube.danmanners.com
  labels:
    provider: Azure
spec:
  type: ExternalName
  externalName: 40.76.165.69
# --- # Digital Ocean has been decomissioned due to their inability to fix my user account.
# kind: Service
# apiVersion: v1
# metadata:
#   name: external-ip-digitalocean
#   namespace: kube-system
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: danmanners.com
#   labels:
#     provider: DigitalOcean
# spec:
#   type: ExternalName
#   externalName: 134.209.45.126
