---
# Source: redis-cluster/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    run: redis-ots
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
    - name: tcp-redis-bus
      port: 16379
      targetPort: tcp-redis-bus
  selector:
    run: redis-ots

