apiVersion: v1
kind: Secret
metadata:
    name: argocd-aws-credentials
    namespace: argocd
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:LA8RY8tmEMa7tnLjIZUByGS6aYx42NZAOlKwVh/h4n7yBkilHIAVqDwRJ9uOgB+CYa8xKj0f7HeYHVoc1+e74EEX3674LaHPNnQ356i9UBZEJvLKbnhm5ONfAx1sKW9Dh5I6crH+6tldGMHSy/XOQyL0MTR+XFA=,iv:voTZ0kIMf9sGXHFO7Xu8db2DIxxL32M2hW5vhUHMAxY=,tag:LzfKiMEpEANmH9kdG/w1EQ==,type:str]
    config: ENC[AES256_GCM,data:XynXJWPTCSZ3fpTlEHtlMYYA6MUZ0jzPx3zZ2cUeEFpz6fJcKEb2kw==,iv:QglbZ9NL7RgwkA9CIHyRAKjdSo5iJnKeSHhue6+SKtU=,tag:TVvLdbH4LSH/wLGevkzUUw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2021-10-17T20:09:57Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwHn20ZfaVdmtjjWmGsMQn7bAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsl6aI3OIf5hOmW2rAgEQgDuMtKlJZ/x47IZA4pENeUKXNnMpVYUEdDfALJ23uEcwZ2GFqir3cVUSP+V0MP9Zk4vBar5pfpnS7H0b3A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-25T22:14:12Z"
    mac: ENC[AES256_GCM,data:k/pP0bBNk8UGPedm4x59BgpMSbLhpx8hXuRF/BlFD8Kw63O5ZCHJVZpTUdbJB+IDBfSwatxLt0T+qz9XrNqDZDmB6uU9b+pSa84uPPtziM+apFNU6UqctTtbYmk9qgpYWdhkREU061fXgm9ck13O8wOcpebv0ITC8UN7p5JgbAo=,iv:hcqEymHvjD+w5e84iPp3u4dZGrJGwaGCHoQTyvM2kak=,tag:WuUEFK6ug9HyGksNtEPGSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
