apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: gitdb-user-creds
    namespace: git
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:MWo+kdyCvTRFi0DxcxoJD/LNMxfpV6htx7PH,iv:3KTVs29uVleFEELlEIjHobnKYjtFe9h+vmZzz7uwXiA=,tag:zIcI8UMIrOmzQYKF5smnYQ==,type:str]
    GITEA_DB_USERNAME: ENC[AES256_GCM,data:wZoHO9zLqK8x+w==,iv:EehSIcA4Bq+qI+xZWfd29x8fKDbc9GpXt7PbTLPQUAs=,tag:9PgUydzDoP6uK+ZRRXWOBg==,type:str]
    GITEA_DB_PASSWORD: ENC[AES256_GCM,data:6D08uwJWDi8xsIs/JpiLQfqzqUuPmK9bUSI5KpQ=,iv:S674LrV/lZEPdYDIBtWVNfQjxYhBCjbvF6tSHkc6cXo=,tag:exOE1AoQawv0DDBMI6oYEw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2023-09-16T04:55:28Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwGSbXgz9LlZEKpkV7IkLX+8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeUbM23bn/cQujNwUAgEQgDsoYWSL4Oy20YYzYiC5wGCUV4UzqJxSXxYQu9XO1+QU6PMM1CiI+t+r44+SA8tJbpPSCy5+IwljIVxyiA==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-16T04:55:28Z"
    mac: ENC[AES256_GCM,data:PiQiQdI19zQUcITdF3uC4+bje9Kfd4k6ioNTiAy4ptxVSa5c2X/qWVF4IRm8ytISwo6lGUfr4o9gMDOD2wyPxYRSPsdYYatnHl8Rc8juY/gXHvxEGw71kO1jq1uM/uWf6Npz/EFbnQSHmU7Ifr0yoOdZ1zPcyYIFuxxv3VyWP1c=,iv:5Y8hXqbk9MV9rGhMMTxp68/1G44nHI8CIt3bGHZxVEo=,tag:JkA2eNqHf22MY/L60C/l2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
