global:
  joinKeySecretName: artifactory-keys
  masterKeySecretName: artifactory-keys
  nodeSelector:
    kubernetes.io/arch: amd64

pipelines:
  enabled: false

rbac:
  create: true

serviceAccount:
  create: true
  automountServiceAccountToken: true

artifactory:
  artifactory:
    # Installer Settings
    installer:
      platform: art-oss-helm

    # Artifactory Settings
    name: artifactory
    image:
      registry: releases-docker.jfrog.io
      repository: jfrog/artifactory-oss
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "4"
        memory: "11Gi"
    javaOpts:
      xms: "2g"
      xmx: "10g"

    persistence:
      enabled: true
      size: 60Gi
      storageClassName: nvme
      accessMode:
        - ReadWriteOnce

    # Credentials
    admin:
      secret: artifactory-creds
      dataKey: bootstrap.creds

  nginx:
    enabled: false
  ingress:
    enabled: false
  postgresql:
    enabled: false

postgresql:
  type: postgresql
  secrets:
    user:
      name: artifactory-db-creds
      key: db-username
    password:
      name: artifactory-db-creds
      key: db-password
    url:
      name: artifactory-db-creds
      key: db-url

filebeat:
  enabled: false

splitServicesToContainers: true
