---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
  labels:
    run: resume-danmanners-com
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  selector:
    matchLabels:
      run: resume-danmanners-com
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: resume-danmanners-com
    spec:
      containers:
      - image: danielmanners/resume-dot-danmanners-dot-com:latest
        imagePullPolicy: Always
        name: resume
        resources:
          limits:
            cpu: "1"
            memory: 160Mi
          requests:
            cpu: 500m
            memory: 96Mi
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        # beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/arch: arm64
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 3