# Source: redis-cluster/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: redis-redis-cluster
    labels:
        app.kubernetes.io/name: redis-cluster
        helm.sh/chart: redis-cluster-7.1.2
        app.kubernetes.io/instance: redis
        app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:Hexs/92iKQ0MEXQ/FIPT1If7C9cg0CckNser8BEp9ag=,iv:TOWpDb3k6yziiocFPN7RsIemxELMT/s1sDN22GMIH0Y=,tag:/uQfPKbTDesWPBoIHjESCw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2022-01-16T04:06:41Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwFIqEo+POUnsC300AVogRRFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMV7ROJKsmtTQAH+PdAgEQgDvXHcoT6dp16ifbN6iPzNNCp1FMsOmL6giXTQmOzh+BQ9qz7RCQigpQRuudVn2CzIJjnn7XZwcPs69jYA==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-16T04:06:41Z"
    mac: ENC[AES256_GCM,data:CdXu7gCkF5XCiw5sfLoVI3qngGYwA1Qvh79u/9nNxfDyQFcRzSRfj9L+m+5a432nXLb2qdcAdpNbikrVvC9QO4rPnkRxuxic+kJ+bcYdpeqPNbL+2ZwwhPkywjNOcOmJ0YBica6Q8RF/edG6zRavQs7ktMJQyMlTQfF82w7ZNfI=,iv:G74djjF/M1MRD9RqT5Zx2u5mbTim4JIU+z6/RNNngyY=,tag:a5vxqCiVinqvf3OwcSrZcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
