---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nda-cert
spec:
  commonName: nda.danmanners.com
  secretName: nda-cert
  dnsNames:
    - nda.danmanners.com
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nda-cert
  namespace: nda
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nda.danmanners.com`)
      kind: Rule
      services:
        - name: nda
          port: 3000
  tls:
    secretName: nda-cert
