kubeProxy:
  enabled: false

prometheus:
  admissionWebhooks:
    enabled: false
    certManager:
      enabled: true
  prometheusSpec:
    resources:
      requests:
        memory: 400Mi

    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: nfs-client
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 20Gi
