kubeProxy:
  enabled: false

prometheus:
  admissionWebhooks:
    enabled: false
    certManager:
      enabled: true
  prometheusSpec:
    resources:
      requests:
        memory: 400Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "ssd"
          resources:
            requests:
              storage: 10Gi

prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
    tlsProxy:
      enabled: false