---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: speaker-reloader
  namespace: metallb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metallb-system:speaker-reloader
  namespace: metallb-system
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments","daemonsets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: speaker-reloader
  namespace: metallb-system
subjects:
  - kind: ServiceAccount
    name: speaker-reloader
    namespace: metallb-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metallb-system:speaker-reloader
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: metallb-restart
  namespace: metallb-system
spec:
  schedule: "0 0,3,6,9,12,15,18,21 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: speaker-reloader
          containers:
            - name: rollout
              image: ghcr.io/onedr0p/kubernetes-kubectl:1.24.3
              imagePullPolicy: IfNotPresent
              command:
                - /usr/local/bin/kubectl
                - rollout
                - restart
                - daemonset
                - speaker
                - --namespace=metallb
