privileged: "true"
DNS1: "10.45.0.1"

serviceDhcp:
  enabled: false

persistentVolumeClaim:
  enabled: true
  storageClass: ssd
  size: 16

serviceTCP:
  loadBalancerIP: 10.56.1.10
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceUDP:
  loadBalancerIP: 10.56.1.10
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceWeb:
  loadBalancerIP: 10.56.1.10
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  type: LoadBalancer
  loadBalancerIP: 10.56.1.10
  port: 53
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# If using in the real world, set up admin.existingSecret instead.
admin:
  existingSecret: password

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 10.45.0.1

extraEnvVars:
  DNSMASQ_USER: root
