# Source: redis-cluster/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: redis-redis-cluster
    labels:
        app.kubernetes.io/name: redis-cluster
        helm.sh/chart: redis-cluster-7.1.2
        app.kubernetes.io/instance: redis
        app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:Xv0YjrUKZD+CKl9M281d33cu694nWFoxmczgbQ2BkhM=,iv:AGcRxsdXXr16CPSQrlx17n+3Z4SMb6XoRGH0xZI7GQ0=,tag:N/GI+WS+y4qh8wDftCX0qQ==,type:str]
    redis_url: ENC[AES256_GCM,data:+l+5J62TVjv7xrh7R7eRvgZTOjp63eqmZy9b2gxB9lP0/N/aI6TSmTEup/6B4Od0xJBZ3geBj/Sk0/JELQp7envC4VWtojHoe1C78XW+cqhNVafmSeJk+StP,iv:CdqrEmQXkk2fb6q+KganWa9C8UjcCZO92DiluOs9IcU=,tag:SxYKTxHWX3h94eCZO+l6JA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2022-01-16T22:01:14Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwE9mXDZQk4n1s5Olb8odwZHAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMOu4ycG0NNIFfbn0JAgEQgDvIJkYcF/oFWms7lZ/iOGQgFhdc0DiHbXWKsa4gjZTPP21wri3PWp9XWD7TxEii8wzfBqNOBUVX/f9ifA==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-16T22:01:14Z"
    mac: ENC[AES256_GCM,data:IL+fO2W1QEAAL7/9HXHhKA++EDuY15zWuiB3RCdZaP1/9Ixg4DqPjliUIpJLSldbGetF/Am0LcoYmfWbahhzkR2zzLFWS0BIoa4DJ0TQAiWr3AVtXJgZ7GRpNM+atuM+OPohr2gRgGbA6aDiUJzrpJL7+W+ibTSTVAjiv1u0GOE=,iv:4mZN4bwll1Z7enYZHbDmzSV1pXJuCuBLK9W8xq85S0Y=,tag:idrfMaO7crHXHOsMiM6vfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
