csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.iscsi"

# add note here about volume expansion requirements
storageClasses:
  - name: zfs-generic-iscsi-csi
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4
    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      #      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
      #      # if doing CHAP
      #      node-db.node.session.auth.authmethod: CHAP
      #      node-db.node.session.auth.username: foo
      #      node-db.node.session.auth.password: bar
      #
      #      # if doing mutual CHAP
      #      node-db.node.session.auth.username_in: baz
      #      node-db.node.session.auth.password_in: bar
      node-publish-secret:
      controller-expand-secret:

volumeSnapshotClasses: []
driver:
  existingConfigSecret: iscsi-driver-config
  config:
    driver: zfs-generic-iscsi