---
apiVersion: v1
kind: Service
metadata:
  name: nda
  namespace: nda
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: nda
---
apiVersion: v1
kind: Service
metadata:
  name: nda-danmanners-extname
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nda.danmanners.com
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app.kubernetes.io/instance: nda
spec:
  type: ExternalName
  externalName: kube.danmanners.com
  sessionAffinity: None
