apiVersion: v1
kind: Secret
metadata:
    name: keycloak
data:
    admin_password: ENC[AES256_GCM,data:MaILA2Nviza6XsM78VZeazSY8sGqCN4C7IpS8qV7abQyKrshfHcduld8O+Q=,iv:wdMeI/ZWQfWZjgFm92f8hkevCpGMdOybex+FzC3QYB8=,tag:8rEzmnAUY/VtFzyDEzSfjg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2021-10-20T02:51:31Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwFdIlw6R5JhlpOn9BVkkoDQAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhqTB1183OzPuh2IxAgEQgDtbZ/l7O1RwO31x+3H0VXiFwLwMsRx2yirkdRD5X4B0K7MVeKMMYJf/oR8oQjxIhXdnULsTTHxQiEX8tg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-20T02:51:31Z"
    mac: ENC[AES256_GCM,data:ctXvkSgezKkSNbfGeTqxSDtWhPGUKX5OlLs5+tWDkwTSx8vDpQ3wA8O1eDglb2WXzx4p3Xss2tXJ4ttsqLRjJTDZMX/J7ERjPzsfZSGPMWG+LUB3nugfI1LJvxeCfbtSwIXlWbAn3CHAPh3y06ORZXpRG2oFXQkU3c3etAUhHik=,iv:GlRwjq2JQVtQLoy5tfWcYotJEZ6I+edkzaWztaLT+m4=,tag:4nRIgsiMi1yAXw9CuUTrXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
