apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workflows-dex-cert
spec:
  secretName: workflows-dex-cert
  dnsNames:
  - dex.homelab.danmanners.com
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
