apiVersion: v1
kind: Secret
metadata:
    name: dex-config
    namespace: argo-workflows
stringData:
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:4FsyJwQbM8RYcGwK6BpwNqmqAik=,iv:whg1HgLbokB5IMQOSa8Q52WAieArsb343j685SJzYLU=,tag:7smoljv5DKMc/wZ3B6wNow==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:kJJip27J7xNS3u2jdMhhvMshhGFE9aSKPW3yI4Rxbnmp1pMUafXTaA==,iv:JHCvejFFiizifSCOtmwtQJLyBSCLOTzvJjG0NzfHUw8=,tag:CRRW13syaytLM2sgJybtjQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2021-12-03T04:35:14Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwGC7AGFyHKx9QsEbEfIkCadAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCrAEHd3HLtFsCfyYAgEQgDtDkFNGjbK/F5Gw0kVK9qjlBRJjw0aXQRjKI1WFvq0ruSaw06KA7J8kT+8c80QUDiHLDa8yxOsSkRmt7Q==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-07T14:50:15Z"
    mac: ENC[AES256_GCM,data:tpvzzexizUxOnmqxvG8cWNhiKud4cbkuB5rFi6u7DphmFqkt1BzJBIjwFwMjFiAB5HMlNCCXOE8a5IgSMADUB1KhlZB8udp/88jSaXu9W+YPX7fyZuZo3wWe6uYTD8gG88/pyMm7b0VMh2v9aOJHz315i32cKm5kmdGqqQVJJGg=,iv:h50ADRQnXbqT4MSZLIYpBSDRVJfA60lH27KmP6nPiAc=,tag:bFG+qcAJUV76uS6/GiLaXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
