kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: argocd.danmanners.com
      http:
        paths:
          - path: /
            backend:
              serviceName: argocd-server
              servicePort: http
