apiVersion: v1
kind: Secret
metadata:
    name: sonar-postgres
stringData:
    pgrootuser: ENC[AES256_GCM,data:EbZrfvyZsZw=,iv:cpSbAzIcPQxlm38GB3Ync8LQfCfX4VoXJrOXAowXFfY=,tag:OZEWHEv86Mm7cQg7MJAGJw==,type:str]
    pgpassword: ENC[AES256_GCM,data:xekGH6ZDH5oOl4uV3Seub14BuEJqGopTgwNABG80CAzLm1OObHvASKHZr1oVynai/vq20+rggZjx0/rPXyPJBA==,iv:vQVrVJGg+5sV6h6xMVhQwHK5Z88AVk3G1MchBU601WU=,tag:SopU8kfB+hKX1bamdrEA+w==,type:str]
    jdbc-url: ENC[AES256_GCM,data:SuH7W+3s/UamxrPDr+LsQA21IpZun+MV/0xjbGx+ZriiIWk1V+ZnYmAX,iv:49CD+xtZm0xUpUUNLT5rH2Lzw6iwBuoXjgW1Q2d9xuQ=,tag:P5lgwfOWcVb8le671dvwoA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2021-12-04T20:22:38Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwFpBdDI147G1L8HkvjfMZTEAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3o9J70AFhxx0Eu1gAgEQgDvr7T2nMeI9i77ID37zCzw399Fc8e0fnGhVYp1H7/5++/Min5cNh+NKcUvCqnWaS04OlDhfmlqhnLMvlg==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-04T20:22:39Z"
    mac: ENC[AES256_GCM,data:35R3Hym2r2SbpmQTxGtZ6DyuzYDyCdDXt9bNRztOD3jAA8/07rKv0ryXVbkKnJW8ofDtthHxbkX/MEy7qKP0OMDEJI4w6rr6aI7dcNHOHSM0soD8kQqHB3pgxaxaUCKDmQEVCEg6NCTXUdGcj6xOaYTT7eqEglW8yoZt0Jf3Gzw=,iv:+lCYR1xpfEpq7dVjEHR4dwTHWO5jQ668VGDX8B+fj+g=,tag:Pxmj8Uk9uSke6we3WGf0sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
