---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "non-disclosure-agreement"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/danmanners/homelab-kube-cluster.git"
    path: manifests/workloads/non-disclosure-agreement
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nda
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
