apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: danmanners-dot-com
  name: danmanners-dot-com
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: resume-dot-danmanners-dot-com
  name: resume-dot-danmanners-dot-com
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: nda
  name: nda
