apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: db-secrets
    namespace: wikijs
stringData:
    POSTGRES_USERNAME: ENC[AES256_GCM,data:ei645muY,iv:bWDnsVUEe6MbZib8TiKv1F9+YEwRSYbJemTtASWtjB4=,tag:Se2vuaS47NYDbY/p4ewqNg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZQvoaLgy2LTVxIBSH7oGX/EBRFw4m4PJQ68Zprc=,iv:dtwYYN2tFkchozVDx/l8FKvahtCIqEMYxLE2tCmiPh4=,tag:XdCOKfV1lSTSwtTTIYZ6tg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:977656673179:key/7e829b85-6fed-4598-b675-8ebeea105c4c
          created_at: "2022-08-07T01:54:20Z"
          enc: AQICAHi1XYvA3EFEGTwFyd0NLI4cRLiZ3o2bNcK2AmDuVl/CEwHjorfOqJ/nmNBxFfKijakgAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCLl4in7ZpXtbsKZsAgEQgDvb+vxS7JsMtsFwMnQXiV87KA4B+TotRpyiWSa4eDixNbpcQEJsPfXY4wBDYdB8gV4kijZeY0hA7dg9ug==
          aws_profile: default
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-07T01:54:20Z"
    mac: ENC[AES256_GCM,data:KttVS8UvHT8Nc/7w76i36plDWbg2taNIATm5e9GhhEknSDLHQTcI72EMmWy1OQFFKC7z3QUeCZXurUWl8H7ELQWBU+Q//LqurHGakLcSHug9u3NGiAp6T0Nv2UZ8G5hLRNGbHLKG+pfAC9ewWAEoCJFN96x2zm9F/83jSP2VyJ8=,iv:Ch5pcTjuGLLr60AhcepBJi7Qvw7HeLU17Q95TGoMe6Y=,tag:HzcPT2WTDfV3iVFlpD5O0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
