kind: Kustomization
namespace: kube-system

helmCharts:
- name: node-feature-discovery
  releaseName: node-feature-discovery
  repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  version: "0.14.0"

resources:
- nfd-worker-conf-cm.yaml
