apiVersion: v1
kind: ConfigMap
metadata:
  name: nfd-worker-conf
  namespace: node-feature-discovery
data:
  nfd-worker.conf: |
    sources:
      custom:
      - name: "blink1"
        matchOn:
        - usbId:
            vendor: ["27b8"]
            # device: ["004"]
