kind: Deployment
apiVersion: apps/v1
metadata:
  name: flux
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: flux
      annotations:
        prometheus.io/port: '3031'
    spec:
      volumes:
        - name: git-key
          secret:
            secretName: flux-git-deploy
            defaultMode: 256
        - name: git-keygen
          emptyDir:
            medium: Memory
      containers:
        - name: flux
          image: 'raspbernetes/flux:1.21.0'
          args:
            - '--memcached-service='
            - '--ssh-keygen-dir=/var/fluxd/keygen'
            - '--git-url=git@github.com:danmanners/homelab-k3s-cluster'
            - '--git-branch=main'
            - '--git-path=namespaces,workloads'
            - '--git-label=flux'
            - '--git-poll-interval=600s'
            - '--git-email=@users.noreply.github.com'
            - '--listen-metrics=:3031'
          ports:
            - containerPort: 3030
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: git-key
              readOnly: true
              mountPath: /etc/fluxd/ssh
            - name: git-keygen
              mountPath: /var/fluxd/keygen
          livenessProbe:
            httpGet:
              path: /api/flux/v6/identity.pub
              port: 3030
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/flux/v6/identity.pub
              port: 3030
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      serviceAccountName: flux
      serviceAccount: flux
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
