---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: argocd-repo-server-build
spec:
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: nfs-client
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  # Make sure the path ends up as ca.crt or buildah would not be able to find
  # it.

  pipelineSpec:
    workspaces:
    - name: shared-workspace
    - name: sslcertdir
      optional: true
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
        - name: output
          workspace: shared-workspace
        params:
        - name: url
          value: https://github.com/kelseyhightower/nocode
      - name: buildah
        taskRef:
          name: buildah
        runAfter:
        - fetch-repository
        workspaces:
        - name: source
          workspace: shared-workspace
        - name: sslcertdir
          workspace: sslcertdir
        params:
        # This will push to the openshift internal registry
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)