global:
  imageRegistry: core.harbor.homelab.danmanners.com/docker.io
  storageClass: ceph-rbd

persistence:
  storageClass: ceph-rbd

service:
  ssh:
    annotations:
      metallb.universe.tf/allow-shared-ip: "globalingress-10.4.240.2"
      metallb.universe.tf/loadBalancerIPs: 10.4.240.2

ingress:
  enabled: true
  apiVersion: networking.k8s.io/v1
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: acme-prod
  hosts:
  - host: git.homelab.danmanners.com
    paths:
    - path: /
      pathType: Prefix

  tls:
  - secretName: gitea-cert
    hosts:
    - git.homelab.danmanners.com

gitea:
  admin:
    existingSecret: gitea-creds
  config:
    APP_NAME: "Not Your Mommas's GitHub"
  additionalConfigFromEnvs:
  - name: GITEA__DATABASE__DB_TYPE
    value: postgresql
  - name: GITEA__DATABASE__HOST
    value: gitdb-rw.git.svc.cluster.local:5432
  - name: GITEA__DATABASE__NAME
    value: gitea
  - name: GITEA__DATABASE__USER
    value: gitdbadmin
  - name: GITEA__DATABASE__PASSWD
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: password

postgresql-ha:
  enabled: false

postgresql:
  enabled: false

