---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system

resources:
  # - ns.yaml 
  - https://raw.githubusercontent.com/open-policy-agent/gatekeeper/v3.7.0/deploy/gatekeeper.yaml
