---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nfd-build
spec:
  workspaces:
    - name: shared-workspace
    - name: varlibcontainers
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/kubernetes-sigs/node-feature-discovery
    - name: manifest-create
      taskRef:
        name: buildah-manifest-create
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: MANIFEST
          value: nfd
    - name: replace-text
      taskRef:
        name: replace-text
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: FILENAME
          value: Dockerfile
        - name: SED_COMMAND
          value: s/golang\:/docker.io\/golang\:/
    - name: build-amd64
      taskRef:
        name: buildah-multiarch-build
      runAfter:
        - manifest-create
        - replace-text
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: MANIFEST
          value: nfd
        - name: ARCH
          value: amd64
        - name: IMAGE
          value: ghcr.io/danmanners/node-feature-discovery:v0.10.1
        - name: BUILD_EXTRA_ARGS
          value: >
            --build-arg BASE_IMAGE_FULL=docker.io/library/debian:buster-slim \
            --build-arg BASE_IMAGE_MINIMAL=gcr.io/distroless/base \
            --build-arg HOSTMOUNT_PREFIX="/" \
            --build-arg VERSION=v0.10.1
    - name: build-arm64
      taskRef:
        name: buildah-multiarch-build
      runAfter:
        - build-amd64
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: MANIFEST
          value: nfd
        - name: ARCH
          value: arm64
        - name: IMAGE
          value: ghcr.io/danmanners/node-feature-discovery:v0.10.1
        - name: BUILD_EXTRA_ARGS
          value: >
            --build-arg BASE_IMAGE_FULL=docker.io/library/debian:buster-slim \
            --build-arg BASE_IMAGE_MINIMAL=gcr.io/distroless/base \
            --build-arg HOSTMOUNT_PREFIX="/" \
            --build-arg VERSION=v0.10.1
  finally:
    - name: push
      taskRef:
        name: buildah-push
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: MANIFEST
          value: nfd
        - name: IMAGE
          value: ghcr.io/danmanners/node-feature-discovery:v0.10.1
