---
- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
  ignore_errors: yes

# Taken from here: https://stackoverflow.com/a/61974725
- name: Enable container features
  replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "cgroup_enable=cpuset"
  - "cgroup_memory=1"
  - "cgroup_enable=memory"
  when: ansible_architecture == "aarch64"

- name: Check if k3s is actually running
  shell: systemctl is-failed k3s-node
  register: k3s_node_status
  ignore_errors: yes

- name: Reboot k3s-nodes if the k3s service is not running
  when: k3s_node_status.stdout != "active"
  reboot:
    reboot_timeout: 300
