---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: danmanners-dot-com
  namespace: danmanners-dot-com
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: danmanners-dot-com
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
