crds:
  install: true
  keep: true

workflow:
  rbac:
    create: true
  serviceAccount:
    create: true

controller:
  image:
    registry: core.harbor.homelab.danmanners.com/quay.io
  workflowNamespaces:
  - default
  - workflows

executor:
  image:
    registry: core.harbor.homelab.danmanners.com/quay.io

server:
  enabled: true
  extraArgs:
  - --auth-mode=sso
  image:
    registry: core.harbor.homelab.danmanners.com/quay.io
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - workflows.homelab.danmanners.com
    tls:
    - secretName: workflows-cert
      hosts:
      - workflows.homelab.danmanners.com
  sso:
    enabled: true
    # insecureSkipVerify: true
    issuer: https://dex.homelab.danmanners.com/dex
    redirectUrl: https://workflows.homelab.danmanners.com/oauth2/callback
    sessionExpiry: "24h"
    clientId:
      name: dex-config
      key: GITHUB_CLIENT_ID
    clientSecret:
      name: dex-config
      key: GITHUB_CLIENT_SECRET
