crds:
  install: true
  keep: true

workflow:
  rbac:
    create: true
  serviceAccount:
    create: true

controller:
  image:
    registry: core.harbor.homelab.danmanners.com/quay.io
  workflowNamespaces:
  - default
  - workflows

executor:
  image:
    registry: core.harbor.homelab.danmanners.com/quay.io

server:
  enabled: true
  image:
    registry: core.harbor.homelab.danmanners.com/quay.io
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - workflows.homelab.danmanners.com
    tls:
    - secretName: workflows-cert
      hosts:
      - workflows.homelab.danmanners.com
