---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft

HelmChartInflationGenerator:
  - chartName: minecraft
    chartRepoUrl: https://itzg.github.io/minecraft-server-charts/
    chartVersion: 3.8.0
    releaseName: minecraft
    releaseNamespace: minecraft
    values: values.yaml

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: minecraft-minecraft
    $patch: delete
