---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft

resources:
  - mc-rendered.yaml

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: minecraft-minecraft
    $patch: delete

